-- Isolated fixtures; the whole transaction rolls back, including auth rows.
begin;
do $$
declare
  u uuid[]; person uuid; league uuid; monthly uuid; duels jsonb; data jsonb; award jsonb; event uuid; n integer; blocked boolean;
begin
  select array_agg(gen_random_uuid()) into u from generate_series(1,13);
  foreach person in array u loop
    insert into auth.users(id,email,role,aud) values(person,'quest-test-'||person::text||'@example.invalid','authenticated','authenticated');
    insert into public.quest_profiles(user_id,username,display_name) values(person,'test_'||left(replace(person::text,'-',''),12),'Fixture traveler') on conflict(user_id) do nothing;
    insert into public.quest_settings(user_id) values(person) on conflict do nothing;
  end loop;
  for n in 2..12 loop
    insert into public.quest_friendships(requester_id,addressee_id,status) values(u[1],u[n],'accepted');
  end loop;
  perform set_config('request.jwt.claim.sub',u[1]::text,true);
  blocked:=false;
  begin perform public.create_quest_contests('Too big','league','week',u[2:11]); exception when raise_exception then blocked:=true; end;
  assert blocked,'League cap must be 10 people including host';
  blocked:=false;
  begin perform public.create_quest_contests('Stranger','league','week',array[u[13]]); exception when raise_exception then blocked:=true; end;
  assert blocked,'Must be accepted friends';
  league := (public.create_quest_contests('Weekly garden','league','week',array[u[2]],'Coffee',false,false)->'ids'->>0)::uuid;
  monthly := (public.create_quest_contests('Monthly garden','league','month',array[u[2]],'',true,false)->'ids'->>0)::uuid;
  blocked:=false;
  begin perform public.start_quest_contest(league); exception when raise_exception then blocked:=true; end;
  assert blocked,'Host must wait for invitation response';
  perform set_config('request.jwt.claim.sub',u[2]::text,true);
  data:=public.get_my_quest_contests();
  assert (select bool_and(value->'activity'='[]'::jsonb) from jsonb_array_elements(data->'contests')),'Invites must not expose activity';
  perform public.respond_quest_contest(league,true,false); perform public.respond_quest_contest(monthly,true,false);
  blocked:=false;
  begin perform public.start_quest_contest(league); exception when raise_exception then blocked:=true; end;
  assert blocked,'Only host can start';
  perform set_config('request.jwt.claim.sub',u[1]::text,true);
  perform public.start_quest_contest(league);perform public.start_quest_contest(monthly);
  assert (select ends_at-starts_at=interval '7 days' from public.quest_contests where id=league),'Week must last 7 days';
  assert (select ends_at=((starts_at at time zone 'UTC')+interval '1 month') at time zone 'UTC' from public.quest_contests where id=monthly),'Month must be calendar month';
  award:=jsonb_build_object('taskId','one','taskName','PRIVATE TEST TASK','creditedXp',20,'tier','standard','dayKey',current_date::text,'weekKey',date_trunc('week',now())::date::text,'completedAt',now());
  update public.quest_settings set progression=jsonb_build_object('taskAwards',jsonb_build_object('domain:one',award),'weeklyBonuses','{}'::jsonb) where user_id=u[2];
  assert (select count(*)=2 from public.quest_contest_entries where user_id=u[2] and active),'Task completion must score in both rounds';
  data:=public.get_my_quest_contests();
  assert data::text not like '%PRIVATE TEST TASK%','Host must not receive a private task name';
  assert (select count(*)=1 from public.quest_contest_notification_events(u[1],now()-interval '1 minute')),'Multiple rounds must produce one friend notification';
  select id into event from public.quest_contest_entries where contest_id=league and user_id=u[2];
  perform set_config('request.jwt.claim.sub',u[2]::text,true);
  perform public.set_quest_contest_privacy(league,true);
  perform set_config('request.jwt.claim.sub',u[1]::text,true);
  data:=public.get_my_quest_contests();
  assert (select value::text like '%PRIVATE TEST TASK%' from jsonb_array_elements(data->'contests') where value->>'id'=league::text),'Consent must reveal the title in that league';
  assert (select value::text not like '%PRIVATE TEST TASK%' from jsonb_array_elements(data->'contests') where value->>'id'=monthly::text),'Consent must not spread to other rounds';
  update public.quest_settings set progression='{}'::jsonb where user_id=u[2];
  assert (select count(*)=0 from public.quest_contest_entries where user_id=u[2] and active),'Undo must remove scores';
  update public.quest_settings set progression=jsonb_build_object('taskAwards',jsonb_build_object('domain:one',award)) where user_id=u[2];
  assert (select count(*)=2 from public.quest_contest_entries where user_id=u[2] and active),'Redo must restore only one entry per round';
  assert (select id=event from public.quest_contest_entries where contest_id=league and user_id=u[2]),'Redo must retain notification identity';
  insert into public.anchors(user_id,id,name,xp_per_day) values(u[2],'fixture-anchor','PRIVATE ANCHOR',5);
  insert into public.anchor_history(user_id,anchor_id,day) values(u[2],'fixture-anchor',current_date);
  assert (select count(*)=1 from public.quest_contest_entries where source='anchor' and user_id=u[2] and active),'Anchor exclusion must be enforced on the server';
  assert (select contest_id=monthly from public.quest_contest_entries where source='anchor' and user_id=u[2]),'Only included-anchor round receives anchor XP';
  delete from public.anchor_history where user_id=u[2] and anchor_id='fixture-anchor';
  assert (select count(*)=0 from public.quest_contest_entries where source='anchor' and user_id=u[2] and active),'Anchor undo must remove score';
  perform set_config('request.jwt.claim.sub',u[13]::text,true);
  assert public.get_my_quest_contests()->'contests'='[]'::jsonb,'Stranger must not see a round';
  blocked:=false;begin perform public.set_quest_contest_privacy(league,true);exception when raise_exception then blocked:=true;end;
  assert blocked,'Stranger cannot change privacy';
  assert not has_table_privilege('authenticated','public.quest_contest_entries','SELECT'),'Raw titles must be inaccessible';
  assert not has_function_privilege('authenticated','public.quest_contest_notification_events(uuid,timestamptz)','EXECUTE'),'Cross-account helper must be private';
  assert not has_function_privilege('anon','public.get_my_quest_contests()','EXECUTE'),'Anonymous RPC denied';
  perform set_config('request.jwt.claim.sub',u[1]::text,true);
  duels:=public.create_quest_contests('Individual','duel','week',u[2:11]);
  assert jsonb_array_length(duels->'ids')=10,'10 friends must make 10 separate rounds';
  assert (select bool_and(q.n=2) from (select count(*) n from public.quest_contest_members where contest_id in(select value::uuid from jsonb_array_elements_text(duels->'ids')) group by contest_id) q),'Individual rounds must contain exactly two people';
  blocked:=false;begin perform public.create_quest_contests('Eleventh','duel','week',array[u[12]]);exception when raise_exception then blocked:=true;end;
  assert blocked,'Individual active limit must be enforced';
  perform set_config('request.jwt.claim.sub',u[2]::text,true);
  data:=public.get_my_quest_contests();
  assert (select count(*)=1 from jsonb_array_elements(data->'contests') where value->>'mode'='duel'),'Opponent cannot see other individual rounds';
  perform public.leave_quest_contest(league);
  assert (select status='left' and not share_task_names from public.quest_contest_members where contest_id=league and user_id=u[2]),'Leaving revokes sharing';
  -- Finish boundaries reject new points and freeze the settled score.
  update public.quest_contests set starts_at=now()-interval '2 months',ends_at=now()-interval '1 second' where id=monthly;
  award:=jsonb_set(award,'{taskName}','"AFTER FINISH"');
  update public.quest_settings set progression=jsonb_build_object('taskAwards',jsonb_build_object('domain:one',award,'domain:two',award)) where user_id=u[2];
  assert not exists(select 1 from public.quest_contest_entries where contest_id=monthly and source_key='domain:two'),'Finished round must not accept points';
end;
$$;
select 'Competition: membership, limits, privacy, scores, undo, anchors, durations and notifications passed' as result;
rollback;
